# Generated by Django 5.1.4 on 2025-01-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_users_is_active_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='posicion',
            new_name='position',
        ),
    ]
