# Generated by Django 5.1.4 on 2025-01-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_posicion_users_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Сотрудник'),
        ),
    ]
