# Generated by Django 5.1.4 on 2025-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_users_is_active_alter_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='apartment',
            field=models.CharField(max_length=10, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='house',
            field=models.CharField(max_length=15, verbose_name='Дом'),
        ),
    ]
